# Generated by Django 5.2.17 on 2026-08-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('AUTHOR', 'Author')], default='USER', max_length=20),
        ),
    ]
